name: Java CI with Maven

# This workflow will run on push and pull request events
on:
  push:
    branches: [ "main" ]
    paths:
      - 'microservices/OrderService/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'microservices/OrderService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/OrderService

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml 