name: UserService CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'microservices/UserService/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'microservices/UserService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/UserService

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: microservices/UserService/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      
    - name: Check code style
      run: npm run lint || true
      
    - name: Run tests
      run: npm test || true 