version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://admin:admin@ita.vittz13.mongodb.net/ITA1?retryWrites=true&w=majority
      - SPRING_DATA_MONGODB_DATABASE=ITA1
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - orderservice-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  orderservice-network:
    driver: bridge

volumes:
  mongodb_data: 