version: '3.8'

services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/userservice
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - userservice-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - userservice-network

volumes:
  mongodb_data:

networks:
  userservice-network:
    driver: bridge 