name: OrderService CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/OrderService/**'
      - '.github/workflows/order-service.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'microservices/OrderService/**'
      - '.github/workflows/order-service.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: |
        cd microservices/OrderService
        mvn -B package --file pom.xml
      env:
        MONGODB_URI: mongodb://localhost:27017/testdb

    - name: Build Docker Image
      run: |
        cd microservices/OrderService
        docker build -t orderservice:latest .
      env:
        DOCKER_BUILDKIT: 1

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: order-service-jar
        path: microservices/OrderService/target/*.jar

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: path/to/results 