name: OrderService CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/OrderService/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'microservices/OrderService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd microservices/OrderService
        mvn -B package --file pom.xml

    - name: Run tests
      run: |
        cd microservices/OrderService
        mvn test

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: orderservice-jar
        path: microservices/OrderService/target/*.jar

  # Uncomment and configure if you want to add deployment
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to production
  #       run: echo "Add your deployment steps here" 