name: UserService CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/UserService/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'microservices/UserService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: microservices/UserService/package-lock.json

    - name: Install dependencies
      run: |
        cd microservices/UserService
        npm ci

    - name: Run tests
      run: |
        cd microservices/UserService
        npm test

    - name: Build
      run: |
        cd microservices/UserService
        npm run build --if-present

    # Optional: Add Docker build step if you want to containerize
    - name: Build Docker image
      run: |
        cd microservices/UserService
        docker build -t userservice .

    # Uncomment and configure if you want to add deployment
    # - name: Deploy
    #   run: |
    #     echo "Add your deployment steps here" 